version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    environment:
      CODACY_PROJECT_TOKEN: b50d7f3860844f70b2c831b8adc22fff
      COVERALLS_REPO_TOKEN: DN73y5QMkUP4bTdmDbkwv4diQwnOKkZBN
    steps:
      - checkout
      - run: bower install
      - run: npm run codacy
      - run: npm run coveralls

workflows:
  version: 2
  test:
    jobs:
      - test